# SETUP
baseurl = "/"
#publishdir = ""
theme = ""
DefaultContentLanguage = "en"
canonifyUrls = "true"
googleAnalytics = ""

[params]
    year = "2018"
    author = "Sahar Heumesser"
    title = "Sahar's Site"
    description = "Sahar's Site Description"
    DateForm = "02.01.2006"
    showReadTime = 1
    showProjects = "false"

[[params.social]]
    title = "Twitter"
    icon = "twitter"
    url = "https://twitter.com/#"
[[params.social]]
    title = "LinkedIn"
    icon = "linkedin"
    url = "https://www.linkedin.com/in/#"

# BLOG
paginate = 3
paginatePath = "page"

[permalinks] 
posts = "post/:title/"

[params.pagination] # for Bootstrap 4
    # These are all optional and default to true
    class = "justify-content-center mt-3 mb-4"      # Add classes to the nav element
    showBeginEnd = false       # If false it will hide the First/Previous/Next/Last if it evaluates to false
    # showFirst = true          # If false it will hide the First page nav button
    firstIndicator = "<i class='fas fa-long-arrow-alt-left'></i>"       # Change the default indicator to something else, like "First" or an icon wrapped in an i element
    # showPrevious = true       # If false it will hide the previous button
    previousIndicator = "<i class='fas fa-chevron-left'></i>"    # Change the default indicator to something else, like "Previous" or an icon wrapped in an i element
    # showNext = true           # True by default - Only "false" will hide the next button
    nextIndicator = "<i class='fas fa-chevron-right'></i>"        # Change the default indicator to something else, like "Next" or an icon wrapped in an i element
    # showLast = true           
    lastIndicator = "<i class='fas fa-long-arrow-alt-right'></i>"        
    # showPageNumbers = true    # If false it will hide the numbering of pages
    # pagesBetweenActive = 2    # How many page numbers to show between the active page - it defaults to 3